### ISSUE TITLE
How to implement into project?

### ISSUE THREAD

**Issue by nileshpol18** [swiftmanagementag/VXWalkthroughViewController#4]
I installed **VXWalkthroughViewController** using **CccoaPods**. I also added **walkthrough_0.png**, _1, _2, _3 files and included **Localizable.strings** file. Implemented **showWalkthrough(**) in my viewConreoller's **viewDidLoad()** method. 
However, just the blank view is presented after I run the application.
Am I missing something? Any help appreciated.

**Comment by glancashire** [comment]
Thanks for trying the pod. Have you tried the included sample? Does it work?

**Comment by nileshpol18** [comment]
Yes, the sample one works fine. However, I am trying to use it in my application. After the walkthrough done, I need to show the login screen. The problem here is that I am not getting walkthrough after I run the application. It is just showing a blank screen.
Is it something that I need to deal with root viewController? Currently, my root viewController is the Login screen.

**Comment by glancashire** [comment]
Hi, can you zip your project and mail it to me, I am more than happy to have a look.

kind regards
graham
➜

Swift Management AG | Managing Partner
St. Alban Vorstadt 104 | 4052 Basel | Switzerland
T ++41 61 385 55 50 | M ++41 79 485 25 20
lancashire@swift.ch | www.swift.ch
